### ISSUE TITLE
wecutil has conflicting option strings

### ISSUE THREAD

**Issue by mans0954** [zenoss/txwinrm#82]
wecutil has two option strings (-p and -s) which conflict with option strings defined in app.py. As a consequence, wecutil crashes when run with the output:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mans0954/python/txwinrm-1.1.26/txwinrm/wecutil.py", line 118, in <module>
    app.main(WecUtility(WecutilStrategy()))
  File "txwinrm/app.py", line 257, in main
    args = _parse_args(utility)
  File "txwinrm/app.py", line 222, in _parse_args
    utility.add_args(parser)
  File "/home/mans0954/python/txwinrm-1.1.26/txwinrm/wecutil.py", line 93, in add_args
    parser.add_argument("--path", "-p", default='Application')
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --password/-p: conflicting option string(s): -p

I suggest that alternative short option strings are provided for the path and select wecutil options (-t and -e perhaps?)

**Comment by mans0954** [comment]
-e is now used for --service in app.py, suggesting -l for --select instead.
